// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfkCKvt6inupEd1ATpV_HDeRdfQJJGkwI',
    appId: '1:190493590716:web:552598f7d5801d7ef6fcb9',
    messagingSenderId: '190493590716',
    projectId: 'galleryapp-5aa1e',
    authDomain: 'galleryapp-5aa1e.firebaseapp.com',
    storageBucket: 'galleryapp-5aa1e.appspot.com',
    measurementId: 'G-FSH0K32PSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVadkBZA2V3EgzqFCuhyDnvoRE5L-y6go',
    appId: '1:190493590716:android:7d6c63bfd2cad991f6fcb9',
    messagingSenderId: '190493590716',
    projectId: 'galleryapp-5aa1e',
    storageBucket: 'galleryapp-5aa1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1uReX7IbWUn5iSVWFO-KDabwzLySoLdk',
    appId: '1:190493590716:ios:526be0b305505efef6fcb9',
    messagingSenderId: '190493590716',
    projectId: 'galleryapp-5aa1e',
    storageBucket: 'galleryapp-5aa1e.appspot.com',
    iosBundleId: 'com.leon.galleryAppNew',
  );
}
