name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
  
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          
      - run: flutter --version

      # - name: Install bundle
      #   run: |
      #     bundle config path vendor/bundle
      #     bundle install --jobs 4 --retry 3
      
      - name: pub get
        working-directory: flutter_app/gallery_app_new
        run: flutter pub get

      
      - name: Distribute app to Alpha track
        env:
          SIGNING_KEY_STORE_PATH: keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          CREDENTIAL_FILE_CONTENT_GG_PLAY: ${{ secrets.CREDENTIAL_FILE_CONTENT_GG_PLAY }}
        working-directory: flutter_app/gallery_app_new/android
        run: fastlane alpha

      # - run: dir
      #   working-directory: flutter_app/gallery_app_new/android/app
        
      # - name: build release
      #   working-directory: flutter_app/gallery_app_new
        # env:
        #    SIGNING_KEY_STORE_PATH: keystore.jks
        #    SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        #    SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        #    SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      #   run: flutter build appbundle
                 
      # - uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_APP_ID}}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}      
      #     groups: testers
      #     file: flutter_app/gallery_app_new/build/app/outputs/bundle/release/app-release.aab
