name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        
      - uses: actions/checkout@v4

      - uses: actions/setup-ruby@v1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
  
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          
      - run: flutter --version
      
      - name: pub get
        working-directory: flutter_app/gallery_app_new
        run: flutter pub get
      
      - name: Distribute app to Alpha track
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          CREDENTIAL_FILE_CONTENT_GG_PLAY: ${{ secrets.CREDENTIAL_FILE_CONTENT_GG_PLAY }}
        working-directory: flutter_app/gallery_app_new/android
        run: fastlane alpha
