name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:        
      # - name: abc
      #   env:
      #     SIGNING_KEY_STORE_PATH: keystore.jks
      #     SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      #     SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      #     SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      #     CREDENTIAL_FILE_CONTENT_GG_PLAY: ${{ secrets.CREDENTIAL_FILE_CONTENT_GG_PLAY }}
      #   run: echo "$CREDENTIAL_FILE_CONTENT_GG_PLAY"
        
      - uses: actions/checkout@v4

      - uses: actions/setup-ruby@v1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
  
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          
      - run: flutter --version

      # - name: Install bundle
      #   run: |
      #     bundle config path vendor/bundle
      #     bundle install --jobs 4 --retry 3
      
      - name: pub get
        working-directory: flutter_app/gallery_app_new
        run: flutter pub get

      
      - name: Distribute app to Alpha track
        env:
          SIGNING_KEY_STORE_PATH: keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          CREDENTIAL_FILE_CONTENT_GG_PLAY: '{"type": "service_account","project_id": "galleryapp-5aa1e","private_key_id": "dfbe9bcd0a85aec0c40b55cb810ad6dafa96c5d9","private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhbSzG/8Q6uuHi\n2jEEWHU8A0MBulVyXBdo0XHOpWnqTK2HFCMp1eXjIse5pNIAn+7aklqQkXKZcFY6\nlwnfo7LuLrcKBbLDU3zeUO5jJgs/LC/1/Bgk4zA+nQ124GGpn89eZw0aaR908ooy\nJguG3f3i29j6KqVBbVEpTGGtONjcxfblWCbeep+1XLcmGCLw60+7p4Sk5qObIbbg\nkw9TRHYZWe/wlO9OLvIAUA75/fPCFHT7aRJelwH5d5q08zQE/Dqk/7FxUuL0fnWA\ne0879BnVBeE77xCnbTVLkwaEWNtte3EMRJYygosu2BY1ML1hZzEXPJTfKul1xT50\nS5+liB6FAgMBAAECggEANIWw4J639C0Vszq+H/KSQgzKgG0POoltZN0jxI9yyYXb\nCnVtKfKt0MmKOl1GFqIszx05X6SbzFdJp/YH9WTZLDiTKhEg0PSzS8MUf+JdzXa4\np/n4ECQk2fnSqMdnydMzyB1/ho9GpoNaIowNtHsli8VIXSUxgrh7KAGlYmwzzuAa\n/YiPlvRnXZAzw11hpS/o8aUOOJ5OUt4/fD12KtD25nTmMqqSN2Tsg++khrW+oty8\nLcH8E1zJ7khRdgGhJsBY0V+tTAn5X9b3uWWbPwBL1vJ73gn4IKasr8oH0r+G0EoE\naaQJspbOlksxlwWBJA30Knj+xj/nqdCUN0ouvx18QwKBgQD5HJ66voVo79vAhTNS\n471tEMk7DcASthy5YUnxBIjwrzrdwd0mMTHe8nLdX8VQJkjinY9CVbJig4lcSSX9\nxtFLNMmWPjUjWyIB49HjgElrWaT1NTNMW1mjDIZ4PAvD8qMM5KEMAKTwbSU9sYYw\nqMyPsMEaZz2C0+jhaz+kfvPRfwKBgQDnqOTtN/DiErDU51b8OAoHwpVCaXKU3Xco\nMMyPoQG5C4i5aq7zwbk3wY2vK3KIY1kdBFiDDOTV/1pTm3BpmO+Vn0N/vQp+qUYx\nxJdv/4Hk1v8Qrv6GJUjWe3WugD3Xrpphfq+UgwTKcbsp0rjbNSLc4IHHLtxLEPHQ\ndZI894PJ+wKBgQCq/esycf5vJl1oC8ZL+kkXKTOHloumDF0xHke76Yn5873rY9vi\nEFiUGUWhENEGkBDthItGVD6LApDxyMAML0GQZt6Mg4zEBRUVyQRULcW3qyPgsLDS\nk822bq2KsGS/Dri+69xjubl90t2COG3MzsEDTKdv8Te2qrCqsoxP5FiGDwKBgChW\nzKZSG2wCfTBVqFv7FiQLyhnqar1pYxpohPZtvvMOAxzmatifXzVKSvW5xxPg2N+o\nphEL6b0p3fy5EHYS34VaWlKgBHfR2htIdGZYQ7IpjfjFwCRz0Z8nmHJuelZYXSGl\nAcYGmor2CvVZcD8bnZqArZiVnF6l8LWwA2sCXryJAoGAZ9lfCG/2BTkOhCGbga0W\n6+mauHEEV9AENqOxBPsWHH2z6zv/P7KRMKZtHVn7TZzW0hr7BP1QKs4qN2/3pWpw\ndvui0c813HEdaqGVyfNvg2NhqT3PH6fZfIj6SPOh/cAVmgJyxTlnI7h6xLcomUxZ\nIMqXKaiU6LRH8q4i6DnTvuw=\n-----END PRIVATE KEY-----\n","client_email": "release-google-play@galleryapp-5aa1e.iam.gserviceaccount.com","client_id": "106587141032678737245","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://oauth2.googleapis.com/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/release-google-play%40galleryapp-5aa1e.iam.gserviceaccount.com","universe_domain": "googleapis.com"}'
        working-directory: flutter_app/gallery_app_new/android
        run: fastlane alpha

      # - run: dir
      #   working-directory: flutter_app/gallery_app_new/android/app
        
      # - name: build release
      #   working-directory: flutter_app/gallery_app_new
        # env:
        #    SIGNING_KEY_STORE_PATH: keystore.jks
        #    SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        #    SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        #    SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      #   run: flutter build appbundle
                 
      # - uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_APP_ID}}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}      
      #     groups: testers
      #     file: flutter_app/gallery_app_new/build/app/outputs/bundle/release/app-release.aab
