name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
  
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - run: flutter --version
      - run: cd flutter_app/gallery_app_new
      - run: flutter pub get
      - name: build release 
        run: flutter build appbundle
      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          #token: ${{secrets.FIREBASE_TOKEN}}   
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}      
          groups: testers
          file: build/app/outputs/bundle/app-release.aab
